CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id TEXT,
  floor INTEGER,
  "user" TEXT,
  "time" TIMESTAMP,
  is_op BOOLEAN,
  content JSONB,
  quote JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (post_id, floor)
);